/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_galera;

import java.awt.Frame;
import java.time.LocalDateTime;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import static java.util.concurrent.TimeUnit.SECONDS;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import desplazable.Desface;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cdani
 */
public class Beta_Galera extends javax.swing.JFrame {

    /**
     * Creates new form Beta_Galera
     */
    public Beta_Galera() {
        initComponents();
        this.mostrarMeseros();
        this.mostrarCategoria();
        this.mostrarProducto();
        try {
            this.cargarComboCategorias();
        } catch (SQLException ex) {
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE, null, ex);
        }
        tID_Productos.setText(""+this.generarIDProducto(id));
        tID_Meseros.setText(""+this.generarIDMeseros(id));
        tIDCategoria.setText(""+this.generarIDCategoria(id));
        jInicioSesion.setVisible(false);
        Productos.setVisible(false);
        Meseros.setVisible(false);
        Mesas.setVisible(false);
        MesaPrincipal.setVisible(false);
        Reporte.setVisible(false);
        Sillas.setVisible(false);
        Comparativa.setVisible(false);
        jPreInformacion.setVisible(false);
        Mesas.setVisible(false);
        this.inicio();
        jTiempo.setText("Ultima sesion: "+tiempo.getDayOfMonth()+"/"+tiempo.getMonth()+"/"+tiempo.getYear()+" "+tiempo.getHour()+":"+tiempo.getMinute()+":"+tiempo.getSecond());
        FechaActualMesero.setText("Fecha actual: "+tiempo.getDayOfMonth()+"/"+tiempo.getMonth()+"/"+tiempo.getYear());
        try {   
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAbdFeel");
        } catch (Exception e) {
        } 
         this.setExtendedState(Frame.MAXIMIZED_BOTH);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInicio = new javax.swing.JPanel();
        Productos = new javax.swing.JPanel();
        bSalirProductos = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        panelMesero6 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        tIDCategoria = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        bRegistrarCategoria = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tTablaCategoria = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        tEscribirCategoria = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tID_Productos = new javax.swing.JTextField();
        tEscribirCategoria2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jCategoriaProducto = new javax.swing.JComboBox<>();
        jLabel68 = new javax.swing.JLabel();
        tEscribirCategoria3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tTablaProducto = new javax.swing.JTable();
        jLabel73 = new javax.swing.JLabel();
        MesaPrincipal = new javax.swing.JPanel();
        bSalirMesasPrincipales = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        panelMesero4 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jCategoria = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        JProducto = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MesaTabla = new javax.swing.JTable();
        jCancelar = new javax.swing.JButton();
        JPagar = new javax.swing.JButton();
        Reporte = new javax.swing.JPanel();
        bSalirReporte = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        panelMesero5 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MesaTabla1 = new javax.swing.JTable();
        jLabel52 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        Comparativa = new javax.swing.JPanel();
        bSalirComparativa = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        panelMesero3 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        Sillas = new javax.swing.JPanel();
        bSalirMesas = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        panelMesero2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        Meseros = new javax.swing.JPanel();
        bSalirMeseros = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tID_Meseros = new javax.swing.JTextField();
        tNombre_Mesero = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelMesero1 = new javax.swing.JPanel();
        FechaActualMesero = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tmostrarMeseros = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tApellidoP = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tApellidoM = new javax.swing.JTextField();
        bRegistrarMesero = new javax.swing.JButton();
        bEliminarMesero = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPreInformacion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTiempo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenu = new javax.swing.JPanel();
        jTitulo = new javax.swing.JLabel();
        jMesas = new javax.swing.JLabel();
        jComparativa = new javax.swing.JLabel();
        jProductos = new javax.swing.JLabel();
        jReporte = new javax.swing.JLabel();
        jMeseros = new javax.swing.JLabel();
        jInicioSesion = new javax.swing.JPanel();
        jTiempo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Mesas = new javax.swing.JPanel();
        Mesa1 = new javax.swing.JLabel();
        Mesa2 = new javax.swing.JLabel();
        Mesa3 = new javax.swing.JLabel();
        Mesa4 = new javax.swing.JLabel();
        Mesa5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInicio.setBackground(new java.awt.Color(255, 255, 255));
        jInicio.setLayout(null);

        Productos.setBackground(new java.awt.Color(255, 255, 255));
        Productos.setForeground(new java.awt.Color(0, 0, 0));
        Productos.setLayout(null);

        bSalirProductos.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bSalirProductos.setForeground(new java.awt.Color(255, 255, 255));
        bSalirProductos.setText("X");
        bSalirProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSalirProductosMouseClicked(evt);
            }
        });
        bSalirProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirProductosActionPerformed(evt);
            }
        });
        Productos.add(bSalirProductos);
        bSalirProductos.setBounds(1290, 10, 90, 60);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        Productos.add(jPanel12);
        jPanel12.setBounds(660, 0, 10, 620);

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        Productos.add(jPanel13);
        jPanel13.setBounds(0, 0, 1400, 10);

        panelMesero6.setBackground(new java.awt.Color(255, 255, 0));
        panelMesero6.setLayout(null);

        jLabel65.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel65.setText("CATEGORIA");
        panelMesero6.add(jLabel65);
        jLabel65.setBounds(160, 10, 320, 80);

        tIDCategoria.setEditable(false);
        tIDCategoria.setBackground(new java.awt.Color(255, 255, 255));
        tIDCategoria.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        panelMesero6.add(tIDCategoria);
        tIDCategoria.setBounds(40, 200, 180, 40);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("ID Categoria");
        panelMesero6.add(jLabel14);
        jLabel14.setBounds(70, 160, 130, 30);

        bRegistrarCategoria.setText("Registrar categoria");
        bRegistrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarCategoriaActionPerformed(evt);
            }
        });
        panelMesero6.add(bRegistrarCategoria);
        bRegistrarCategoria.setBounds(170, 280, 270, 60);

        tTablaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tTablaCategoria);

        panelMesero6.add(jScrollPane3);
        jScrollPane3.setBounds(80, 390, 450, 150);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Escribe el nombre de tu categoria:");
        panelMesero6.add(jLabel15);
        jLabel15.setBounds(320, 160, 310, 30);

        tEscribirCategoria.setBackground(new java.awt.Color(255, 255, 255));
        tEscribirCategoria.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        panelMesero6.add(tEscribirCategoria);
        tEscribirCategoria.setBounds(320, 200, 290, 40);

        Productos.add(panelMesero6);
        panelMesero6.setBounds(0, 0, 660, 620);

        jLabel66.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel66.setText("PRODUCTO");
        Productos.add(jLabel66);
        jLabel66.setBounds(910, 10, 290, 80);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Id producto:");
        Productos.add(jLabel13);
        jLabel13.setBounds(730, 110, 120, 30);

        tID_Productos.setEditable(false);
        tID_Productos.setBackground(new java.awt.Color(255, 255, 255));
        tID_Productos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Productos.add(tID_Productos);
        tID_Productos.setBounds(710, 150, 150, 40);

        tEscribirCategoria2.setBackground(new java.awt.Color(255, 255, 255));
        tEscribirCategoria2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        tEscribirCategoria2.setForeground(new java.awt.Color(0, 0, 0));
        Productos.add(tEscribirCategoria2);
        tEscribirCategoria2.setBounds(1070, 270, 170, 40);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Precio:");
        Productos.add(jLabel17);
        jLabel17.setBounds(1120, 230, 70, 30);

        jLabel67.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 0, 0));
        jLabel67.setText("Nombre del producto:");
        Productos.add(jLabel67);
        jLabel67.setBounds(1040, 110, 210, 30);

        jCategoriaProducto.setBackground(new java.awt.Color(255, 255, 255));
        jCategoriaProducto.setForeground(new java.awt.Color(0, 0, 0));
        Productos.add(jCategoriaProducto);
        jCategoriaProducto.setBounds(700, 270, 250, 40);

        jLabel68.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(0, 0, 0));
        jLabel68.setText("Categoria del producto:");
        Productos.add(jLabel68);
        jLabel68.setBounds(720, 230, 210, 30);

        tEscribirCategoria3.setBackground(new java.awt.Color(255, 255, 255));
        tEscribirCategoria3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Productos.add(tEscribirCategoria3);
        tEscribirCategoria3.setBounds(990, 150, 300, 40);

        jButton1.setText("Registrar productos");
        Productos.add(jButton1);
        jButton1.setBounds(890, 350, 320, 60);

        tTablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tTablaProducto);

        Productos.add(jScrollPane5);
        jScrollPane5.setBounds(750, 470, 560, 90);

        jLabel73.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel73.setText("VERSION INTERFACE 1.2");
        Productos.add(jLabel73);
        jLabel73.setBounds(1150, 590, 250, 30);

        jInicio.add(Productos);
        Productos.setBounds(0, 90, 1380, 620);

        MesaPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        MesaPrincipal.setLayout(null);

        bSalirMesasPrincipales.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bSalirMesasPrincipales.setForeground(new java.awt.Color(255, 255, 255));
        bSalirMesasPrincipales.setText("X");
        bSalirMesasPrincipales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirMesasPrincipalesActionPerformed(evt);
            }
        });
        MesaPrincipal.add(bSalirMesasPrincipales);
        bSalirMesasPrincipales.setBounds(1290, 10, 90, 60);

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel33.setText("Mesas (NUMBER)");
        MesaPrincipal.add(jLabel33);
        jLabel33.setBounds(610, 0, 420, 80);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        MesaPrincipal.add(jPanel8);
        jPanel8.setBounds(180, 10, 10, 610);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        MesaPrincipal.add(jPanel9);
        jPanel9.setBounds(0, 0, 1400, 10);

        panelMesero4.setBackground(new java.awt.Color(255, 255, 0));
        panelMesero4.setLayout(null);

        jLabel50.setBackground(new java.awt.Color(0, 0, 0));
        jLabel50.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel50.setText("M");
        panelMesero4.add(jLabel50);
        jLabel50.setBounds(50, 20, 120, 90);

        jLabel51.setBackground(new java.awt.Color(0, 0, 0));
        jLabel51.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel51.setText("E");
        panelMesero4.add(jLabel51);
        jLabel51.setBounds(50, 140, 100, 90);

        jLabel55.setBackground(new java.awt.Color(0, 0, 0));
        jLabel55.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel55.setText("S");
        panelMesero4.add(jLabel55);
        jLabel55.setBounds(50, 260, 70, 90);

        jLabel56.setBackground(new java.awt.Color(0, 0, 0));
        jLabel56.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel56.setText("A");
        panelMesero4.add(jLabel56);
        jLabel56.setBounds(50, 380, 100, 90);

        jLabel57.setBackground(new java.awt.Color(0, 0, 0));
        jLabel57.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel57.setText("S");
        panelMesero4.add(jLabel57);
        jLabel57.setBounds(50, 500, 100, 90);

        MesaPrincipal.add(panelMesero4);
        panelMesero4.setBounds(0, 0, 180, 620);

        jLabel53.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel53.setText("VERSION INTERFACE 1.2");
        MesaPrincipal.add(jLabel53);
        jLabel53.setBounds(1150, 580, 250, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Agregar pedido");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        MesaPrincipal.add(jButton5);
        jButton5.setBounds(650, 290, 240, 50);

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel34.setText("Categoria:");
        MesaPrincipal.add(jLabel34);
        jLabel34.setBounds(310, 130, 120, 32);

        jCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCategoriaActionPerformed(evt);
            }
        });
        MesaPrincipal.add(jCategoria);
        jCategoria.setBounds(470, 140, 190, 26);

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel35.setText("Producto:");
        MesaPrincipal.add(jLabel35);
        jLabel35.setBounds(800, 140, 140, 32);

        JProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MesaPrincipal.add(JProducto);
        JProducto.setBounds(970, 150, 200, 26);

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel36.setText("Cantidad:");
        MesaPrincipal.add(jLabel36);
        jLabel36.setBounds(390, 230, 120, 30);
        MesaPrincipal.add(jSpinner1);
        jSpinner1.setBounds(550, 230, 40, 30);

        jLabel47.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel47.setText("Precio:");
        MesaPrincipal.add(jLabel47);
        jLabel47.setBounds(890, 230, 90, 32);

        jLabel48.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel48.setText("$$$$");
        MesaPrincipal.add(jLabel48);
        jLabel48.setBounds(990, 230, 70, 32);

        MesaTabla.setBackground(new java.awt.Color(255, 255, 0));
        MesaTabla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MesaTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(MesaTabla);

        MesaPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(210, 370, 1150, 90);

        jCancelar.setBackground(new java.awt.Color(255, 255, 0));
        jCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCancelar.setText("Cancelar pedido");
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });
        MesaPrincipal.add(jCancelar);
        jCancelar.setBounds(530, 520, 190, 80);

        JPagar.setBackground(new java.awt.Color(255, 255, 0));
        JPagar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JPagar.setText("Pagar pedido");
        MesaPrincipal.add(JPagar);
        JPagar.setBounds(860, 520, 180, 80);

        jInicio.add(MesaPrincipal);
        MesaPrincipal.setBounds(0, 90, 1380, 620);

        Reporte.setBackground(new java.awt.Color(255, 255, 255));
        Reporte.setLayout(null);

        bSalirReporte.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bSalirReporte.setForeground(new java.awt.Color(255, 255, 255));
        bSalirReporte.setText("X");
        bSalirReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSalirReporteMouseClicked(evt);
            }
        });
        bSalirReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirReporteActionPerformed(evt);
            }
        });
        Reporte.add(bSalirReporte);
        bSalirReporte.setBounds(1280, 10, 90, 60);

        jLabel49.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel49.setText("Reporte");
        Reporte.add(jLabel49);
        jLabel49.setBounds(700, 10, 190, 80);

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        Reporte.add(jPanel10);
        jPanel10.setBounds(180, 10, 10, 610);

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        Reporte.add(jPanel11);
        jPanel11.setBounds(0, 0, 1400, 10);

        panelMesero5.setBackground(new java.awt.Color(255, 255, 0));
        panelMesero5.setLayout(null);

        jLabel58.setBackground(new java.awt.Color(0, 0, 0));
        jLabel58.setFont(new java.awt.Font("Dialog", 1, 65)); // NOI18N
        jLabel58.setText("E");
        panelMesero5.add(jLabel58);
        jLabel58.setBounds(60, 530, 70, 80);

        jLabel59.setBackground(new java.awt.Color(0, 0, 0));
        jLabel59.setFont(new java.awt.Font("Dialog", 1, 65)); // NOI18N
        jLabel59.setText("R");
        panelMesero5.add(jLabel59);
        jLabel59.setBounds(70, 10, 90, 80);

        jLabel60.setBackground(new java.awt.Color(0, 0, 0));
        jLabel60.setFont(new java.awt.Font("Dialog", 1, 65)); // NOI18N
        jLabel60.setText("E");
        panelMesero5.add(jLabel60);
        jLabel60.setBounds(70, 90, 90, 80);

        jLabel61.setBackground(new java.awt.Color(0, 0, 0));
        jLabel61.setFont(new java.awt.Font("Dialog", 1, 65)); // NOI18N
        jLabel61.setText("P");
        panelMesero5.add(jLabel61);
        jLabel61.setBounds(70, 180, 100, 80);

        jLabel62.setBackground(new java.awt.Color(0, 0, 0));
        jLabel62.setFont(new java.awt.Font("Dialog", 1, 65)); // NOI18N
        jLabel62.setText("O");
        panelMesero5.add(jLabel62);
        jLabel62.setBounds(60, 270, 70, 80);

        jLabel63.setBackground(new java.awt.Color(0, 0, 0));
        jLabel63.setFont(new java.awt.Font("Dialog", 1, 65)); // NOI18N
        jLabel63.setText("R");
        panelMesero5.add(jLabel63);
        jLabel63.setBounds(60, 360, 70, 80);

        jLabel64.setBackground(new java.awt.Color(0, 0, 0));
        jLabel64.setFont(new java.awt.Font("Dialog", 1, 65)); // NOI18N
        jLabel64.setText("T");
        panelMesero5.add(jLabel64);
        jLabel64.setBounds(60, 450, 70, 80);

        Reporte.add(panelMesero5);
        panelMesero5.setBounds(0, 0, 180, 620);

        jLabel54.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel54.setText("VERSION INTERFACE 1.2");
        Reporte.add(jLabel54);
        jLabel54.setBounds(1150, 580, 250, 30);

        jButton6.setBackground(new java.awt.Color(255, 255, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Enviar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Reporte.add(jButton6);
        jButton6.setBounds(940, 160, 240, 50);

        MesaTabla1.setBackground(new java.awt.Color(255, 255, 0));
        MesaTabla1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MesaTabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(MesaTabla1);

        Reporte.add(jScrollPane2);
        jScrollPane2.setBounds(210, 310, 1140, 220);

        jLabel52.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel52.setText("Fecha a generar:");
        Reporte.add(jLabel52);
        jLabel52.setBounds(420, 160, 200, 40);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Reporte.add(jComboBox8);
        jComboBox8.setBounds(640, 170, 230, 30);

        jInicio.add(Reporte);
        Reporte.setBounds(0, 90, 1370, 620);

        Comparativa.setBackground(new java.awt.Color(255, 255, 255));
        Comparativa.setLayout(null);

        bSalirComparativa.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bSalirComparativa.setForeground(new java.awt.Color(255, 255, 255));
        bSalirComparativa.setText("X");
        bSalirComparativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirComparativaActionPerformed(evt);
            }
        });
        Comparativa.add(bSalirComparativa);
        bSalirComparativa.setBounds(1280, 10, 90, 60);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel21.setText("Comparativa");
        Comparativa.add(jLabel21);
        jLabel21.setBounds(670, 0, 400, 80);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        Comparativa.add(jPanel6);
        jPanel6.setBounds(360, 10, 10, 610);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        Comparativa.add(jPanel7);
        jPanel7.setBounds(0, 0, 1400, 10);

        panelMesero3.setBackground(new java.awt.Color(255, 255, 0));
        panelMesero3.setLayout(null);

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel37.setText("------------RELLENO-------------");
        panelMesero3.add(jLabel37);
        jLabel37.setBounds(50, 560, 250, 40);

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel42.setText("Resultado comparativa:");
        panelMesero3.add(jLabel42);
        jLabel42.setBounds(40, 30, 290, 40);

        jLabel43.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel43.setText("Producto 1 (Name): $$$");
        panelMesero3.add(jLabel43);
        jLabel43.setBounds(30, 140, 210, 40);

        jLabel44.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel44.setText("Producto 2 (Name): $$$");
        panelMesero3.add(jLabel44);
        jLabel44.setBounds(30, 230, 220, 40);

        jLabel45.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel45.setText("------------RELLENO-------------");
        panelMesero3.add(jLabel45);
        jLabel45.setBounds(50, 380, 250, 40);

        jLabel46.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel46.setText("------------RELLENO-------------");
        panelMesero3.add(jLabel46);
        jLabel46.setBounds(50, 470, 250, 40);

        Comparativa.add(panelMesero3);
        panelMesero3.setBounds(0, 0, 360, 620);

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel38.setText("VERSION INTERFACE 1.1");
        Comparativa.add(jLabel38);
        jLabel38.setBounds(1150, 580, 250, 30);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Comparativa.add(jComboBox5);
        jComboBox5.setBounds(900, 160, 270, 30);

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel39.setText("Seleccione el producto 1:");
        Comparativa.add(jLabel39);
        jLabel39.setBounds(420, 310, 300, 70);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Comparativa.add(jComboBox6);
        jComboBox6.setBounds(730, 330, 270, 30);

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel40.setText("Seleccione el producto 2:");
        Comparativa.add(jLabel40);
        jLabel40.setBounds(440, 420, 300, 70);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Comparativa.add(jComboBox7);
        jComboBox7.setBounds(750, 440, 270, 30);

        jLabel8.setText("La cantidad de producto: number_producto");
        Comparativa.add(jLabel8);
        jLabel8.setBounds(1050, 430, 290, 40);

        jLabel27.setText("La cantidad de producto: number_producto");
        Comparativa.add(jLabel27);
        jLabel27.setBounds(1040, 320, 290, 40);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        Comparativa.add(jSeparator1);
        jSeparator1.setBounds(370, 242, 1000, 10);

        jButton3.setText("Enviar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Comparativa.add(jButton3);
        jButton3.setBounds(700, 550, 240, 50);

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel41.setText("Seleccione la categoria del producto:");
        Comparativa.add(jLabel41);
        jLabel41.setBounds(450, 140, 430, 70);

        jInicio.add(Comparativa);
        Comparativa.setBounds(0, 90, 1370, 620);

        Sillas.setBackground(new java.awt.Color(255, 255, 255));
        Sillas.setLayout(null);

        bSalirMesas.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bSalirMesas.setForeground(new java.awt.Color(255, 255, 255));
        bSalirMesas.setText("X");
        bSalirMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirMesasActionPerformed(evt);
            }
        });
        Sillas.add(bSalirMesas);
        bSalirMesas.setBounds(1280, 10, 90, 60);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel20.setText("JUNTAR MESAS");
        Sillas.add(jLabel20);
        jLabel20.setBounds(620, 0, 400, 80);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        Sillas.add(jPanel4);
        jPanel4.setBounds(140, 10, 10, 610);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        Sillas.add(jPanel5);
        jPanel5.setBounds(0, 0, 1400, 10);

        panelMesero2.setBackground(new java.awt.Color(255, 255, 0));
        panelMesero2.setLayout(null);

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel22.setText("S");
        panelMesero2.add(jLabel22);
        jLabel22.setBounds(30, 500, 100, 90);

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel23.setText("M");
        panelMesero2.add(jLabel23);
        jLabel23.setBounds(20, 20, 100, 90);

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel24.setText("E");
        panelMesero2.add(jLabel24);
        jLabel24.setBounds(30, 140, 100, 90);

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel25.setText("S");
        panelMesero2.add(jLabel25);
        jLabel25.setBounds(30, 260, 70, 90);

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel26.setText("A");
        panelMesero2.add(jLabel26);
        jLabel26.setBounds(30, 380, 100, 90);

        Sillas.add(panelMesero2);
        panelMesero2.setBounds(0, 0, 140, 620);

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel28.setText("Seleccione las mesa 1:");
        Sillas.add(jLabel28);
        jLabel28.setBounds(220, 130, 270, 60);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Juntar");
        Sillas.add(jButton4);
        jButton4.setBounds(670, 390, 220, 70);

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel31.setText("VERSION INTERFACE 1.1");
        Sillas.add(jLabel31);
        jLabel31.setBounds(1150, 580, 250, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Sillas.add(jComboBox1);
        jComboBox1.setBounds(1040, 140, 140, 40);

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel32.setText("Seleccione las mesa 2:");
        Sillas.add(jLabel32);
        jLabel32.setBounds(770, 130, 270, 60);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Sillas.add(jComboBox2);
        jComboBox2.setBounds(500, 140, 140, 40);

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel29.setText("Seleccione las mesa 3:");
        Sillas.add(jLabel29);
        jLabel29.setBounds(220, 240, 270, 60);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Sillas.add(jComboBox3);
        jComboBox3.setBounds(500, 250, 140, 40);

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel30.setText("Seleccione las mesa 4:");
        Sillas.add(jLabel30);
        jLabel30.setBounds(770, 240, 270, 60);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Sillas.add(jComboBox4);
        jComboBox4.setBounds(1050, 250, 140, 40);

        jInicio.add(Sillas);
        Sillas.setBounds(0, 90, 1370, 620);

        Meseros.setBackground(new java.awt.Color(255, 255, 255));
        Meseros.setLayout(null);

        bSalirMeseros.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bSalirMeseros.setForeground(new java.awt.Color(255, 255, 255));
        bSalirMeseros.setText("X");
        bSalirMeseros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirMeserosActionPerformed(evt);
            }
        });
        Meseros.add(bSalirMeseros);
        bSalirMeseros.setBounds(1280, 10, 90, 60);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel7.setText("REGISTRO MESEROS");
        Meseros.add(jLabel7);
        jLabel7.setBounds(620, 0, 520, 80);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("ID unico:");
        Meseros.add(jLabel9);
        jLabel9.setBounds(990, 140, 110, 50);

        tID_Meseros.setEditable(false);
        tID_Meseros.setBackground(new java.awt.Color(255, 255, 255));
        tID_Meseros.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tID_Meseros.setToolTipText("Escriba");
        Meseros.add(tID_Meseros);
        tID_Meseros.setBounds(1100, 150, 210, 30);

        tNombre_Mesero.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tNombre_Mesero.setToolTipText("Escriba");
        tNombre_Mesero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tNombre_MeseroFocusGained(evt);
            }
        });
        Meseros.add(tNombre_Mesero);
        tNombre_Mesero.setBounds(670, 150, 260, 30);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        Meseros.add(jPanel3);
        jPanel3.setBounds(370, 10, 10, 610);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        Meseros.add(jPanel2);
        jPanel2.setBounds(0, 0, 1400, 10);

        panelMesero1.setBackground(new java.awt.Color(255, 255, 0));
        panelMesero1.setLayout(null);

        FechaActualMesero.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FechaActualMesero.setText("Fecha actual:");
        panelMesero1.add(FechaActualMesero);
        FechaActualMesero.setBounds(20, 440, 330, 40);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Meseros actuales");
        panelMesero1.add(jLabel18);
        jLabel18.setBounds(30, 10, 270, 50);

        tmostrarMeseros.setBackground(new java.awt.Color(255, 255, 0));
        tmostrarMeseros.setForeground(new java.awt.Color(0, 0, 0));
        tmostrarMeseros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Meseros"
            }
        ));
        jScrollPane4.setViewportView(tmostrarMeseros);

        panelMesero1.add(jScrollPane4);
        jScrollPane4.setBounds(20, 73, 330, 350);

        Meseros.add(panelMesero1);
        panelMesero1.setBounds(0, 0, 370, 620);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Nombre(s) del mesero:");
        Meseros.add(jLabel11);
        jLabel11.setBounds(400, 140, 270, 50);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("Apellido paterno:");
        Meseros.add(jLabel12);
        jLabel12.setBounds(410, 290, 210, 50);

        tApellidoP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tApellidoP.setToolTipText("Escriba");
        Meseros.add(tApellidoP);
        tApellidoP.setBounds(620, 300, 220, 30);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setText("Apellido materno:");
        Meseros.add(jLabel19);
        jLabel19.setBounds(890, 290, 210, 50);

        tApellidoM.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tApellidoM.setToolTipText("Escriba");
        Meseros.add(tApellidoM);
        tApellidoM.setBounds(1100, 300, 210, 30);

        bRegistrarMesero.setBackground(new java.awt.Color(255, 255, 255));
        bRegistrarMesero.setText("Registrar");
        bRegistrarMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarMeseroActionPerformed(evt);
            }
        });
        Meseros.add(bRegistrarMesero);
        bRegistrarMesero.setBounds(970, 460, 220, 70);

        bEliminarMesero.setBackground(new java.awt.Color(255, 255, 255));
        bEliminarMesero.setText("Eliminar usuario");
        bEliminarMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarMeseroActionPerformed(evt);
            }
        });
        Meseros.add(bEliminarMesero);
        bEliminarMesero.setBounds(600, 460, 220, 70);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("VERSION INTERFACE 1.2");
        Meseros.add(jLabel10);
        jLabel10.setBounds(1150, 580, 250, 30);

        jInicio.add(Meseros);
        Meseros.setBounds(0, 90, 1370, 620);

        jPreInformacion.setBackground(new java.awt.Color(0, 153, 255));
        jPreInformacion.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Gastado: $0");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 220, 120, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Numero de mesa: number");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 150, 240, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Estatus: Activo");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 80, 150, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Informacion prevista de la mesa");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 10, 320, 30);

        jPreInformacion.add(jPanel1);
        jPanel1.setBounds(20, 10, 320, 600);

        jInicio.add(jPreInformacion);
        jPreInformacion.setBounds(1020, 90, 360, 620);

        jTiempo1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jInicio.add(jTiempo1);
        jTiempo1.setBounds(1150, 680, 230, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("VERSION BETA 1.20");
        jInicio.add(jLabel2);
        jLabel2.setBounds(1130, 650, 240, 50);

        jMenu.setBackground(new java.awt.Color(255, 255, 0));
        jMenu.setLayout(null);

        jTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/1663952285593 (2).png"))); // NOI18N
        jTitulo.setText("PROJECT_GALERAS");
        jMenu.add(jTitulo);
        jTitulo.setBounds(20, 0, 440, 90);

        jMesas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/imagen_2022-09-26_113114959.png"))); // NOI18N
        jMesas.setText("Mesas");
        jMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMesasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMesasMouseExited(evt);
            }
        });
        jMenu.add(jMesas);
        jMesas.setBounds(480, 30, 100, 30);

        jComparativa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComparativa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/imagen_2022-10-03_100700234.png"))); // NOI18N
        jComparativa.setText("Comparativa");
        jComparativa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComparativaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComparativaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComparativaMouseExited(evt);
            }
        });
        jMenu.add(jComparativa);
        jComparativa.setBounds(610, 30, 160, 30);

        jProductos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/imagen_2022-10-03_094538812.png"))); // NOI18N
        jProductos.setText("Productos");
        jProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jProductosMouseExited(evt);
            }
        });
        jMenu.add(jProductos);
        jProductos.setBounds(800, 30, 130, 30);

        jReporte.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/imagen_2022-09-26_235325867.png"))); // NOI18N
        jReporte.setText("Reporte");
        jReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jReporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jReporteMouseExited(evt);
            }
        });
        jMenu.add(jReporte);
        jReporte.setBounds(970, 30, 110, 30);

        jMeseros.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMeseros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/imagen_2022-10-19_100343372.png"))); // NOI18N
        jMeseros.setText("Meseros");
        jMeseros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMeserosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMeserosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMeserosMouseExited(evt);
            }
        });
        jMenu.add(jMeseros);
        jMeseros.setBounds(1120, 30, 110, 30);

        jInicio.add(jMenu);
        jMenu.setBounds(10, 0, 1370, 90);

        jInicioSesion.setLayout(null);

        jTiempo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jInicioSesion.add(jTiempo);
        jTiempo.setBounds(460, 60, 480, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3.setText("BIENVENIDO A GALERAS");
        jInicioSesion.add(jLabel3);
        jLabel3.setBounds(390, 0, 590, 60);

        jInicio.add(jInicioSesion);
        jInicioSesion.setBounds(10, 310, 1370, 110);

        Mesas.setBackground(new java.awt.Color(255, 255, 255));
        Mesas.setLayout(null);

        Mesa1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Mesa1.setText("Mesa 1");
        Mesa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mesa1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mesa1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Mesa1MouseExited(evt);
            }
        });
        Mesas.add(Mesa1);
        Mesa1.setBounds(30, 40, 80, 30);

        Mesa2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Mesa2.setText("Mesa 2");
        Mesa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mesa2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mesa2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Mesa2MouseExited(evt);
            }
        });
        Mesas.add(Mesa2);
        Mesa2.setBounds(150, 40, 90, 30);

        Mesa3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Mesa3.setText("Mesa 3");
        Mesa3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mesa3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mesa3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Mesa3MouseExited(evt);
            }
        });
        Mesas.add(Mesa3);
        Mesa3.setBounds(270, 40, 90, 30);

        Mesa4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Mesa4.setText("Mesa 4");
        Mesa4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mesa4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mesa4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Mesa4MouseExited(evt);
            }
        });
        Mesas.add(Mesa4);
        Mesa4.setBounds(390, 40, 90, 30);

        Mesa5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Mesa5.setText("Mesa 5");
        Mesa5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mesa5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mesa5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Mesa5MouseExited(evt);
            }
        });
        Mesas.add(Mesa5);
        Mesa5.setBounds(520, 40, 90, 30);

        jInicio.add(Mesas);
        Mesas.setBounds(10, 90, 1370, 620);

        getContentPane().add(jInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1380, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMesasMouseEntered
        jMenu.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jMesasMouseEntered

    private void jMesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMesasMouseExited
        jMenu.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMesasMouseExited

    private void jMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMesasMouseClicked
        Productos.setVisible(false);
        Sillas.setVisible(true);
        Meseros.setVisible(false);
        Reporte.setVisible(false);
        MesaPrincipal.setVisible(false);
        Mesas.setVisible(false);
        Comparativa.setVisible(false);
    }//GEN-LAST:event_jMesasMouseClicked

    private void jComparativaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComparativaMouseClicked
        Productos.setVisible(false);
        Comparativa.setVisible(true);
        Sillas.setVisible(false);
        Meseros.setVisible(false);
        Reporte.setVisible(false);
        MesaPrincipal.setVisible(false);
        Mesas.setVisible(false);
    }//GEN-LAST:event_jComparativaMouseClicked

    private void jComparativaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComparativaMouseEntered
        jMenu.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jComparativaMouseEntered

    private void jComparativaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComparativaMouseExited
        jMenu.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jComparativaMouseExited

    private void jProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProductosMouseClicked
        Productos.setVisible(true);
        Reporte.setVisible(false);
        Meseros.setVisible(false);
        MesaPrincipal.setVisible(false);
        Comparativa.setVisible(false);
        Sillas.setVisible(false);
        Mesas.setVisible(false);
    }//GEN-LAST:event_jProductosMouseClicked

    private void jProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProductosMouseEntered
        jMenu.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jProductosMouseEntered

    private void jProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProductosMouseExited
        jMenu.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jProductosMouseExited

    private void jReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jReporteMouseClicked
        Productos.setVisible(false);
        Reporte.setVisible(true);
        Meseros.setVisible(false);
        MesaPrincipal.setVisible(false);
        Comparativa.setVisible(false);
        Sillas.setVisible(false);
        Mesas.setVisible(false);
    }//GEN-LAST:event_jReporteMouseClicked

    private void jReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jReporteMouseEntered
        jMenu.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jReporteMouseEntered

    private void jReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jReporteMouseExited
        jMenu.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jReporteMouseExited

    private void Mesa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa1MouseClicked
        Mesas.setVisible(false);
        MesaPrincipal.setVisible(true);
        
    }//GEN-LAST:event_Mesa1MouseClicked

    private void Mesa1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa1MouseEntered
        Mesas.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jPreInformacion.setVisible(true);
    }//GEN-LAST:event_Mesa1MouseEntered

    private void Mesa1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa1MouseExited
        Mesas.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        jPreInformacion.setVisible(false);
    }//GEN-LAST:event_Mesa1MouseExited

    private void Mesa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa2MouseClicked

    }//GEN-LAST:event_Mesa2MouseClicked

    private void Mesa2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa2MouseEntered
        Mesas.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Mesa2MouseEntered

    private void Mesa2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa2MouseExited
        Mesas.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }//GEN-LAST:event_Mesa2MouseExited

    private void Mesa3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa3MouseClicked

    }//GEN-LAST:event_Mesa3MouseClicked

    private void Mesa3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa3MouseEntered
        Mesas.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Mesa3MouseEntered

    private void Mesa3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa3MouseExited
        Mesas.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_Mesa3MouseExited

    private void Mesa4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa4MouseClicked

    }//GEN-LAST:event_Mesa4MouseClicked

    private void Mesa4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa4MouseEntered
        Mesas.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Mesa4MouseEntered

    private void Mesa4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa4MouseExited
        Mesas.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_Mesa4MouseExited

    private void Mesa5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa5MouseClicked

    }//GEN-LAST:event_Mesa5MouseClicked

    private void Mesa5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa5MouseEntered
        
    }//GEN-LAST:event_Mesa5MouseEntered

    private void Mesa5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa5MouseExited
 ;
    }//GEN-LAST:event_Mesa5MouseExited

    private void jMeserosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMeserosMouseClicked
        Productos.setVisible(false);
        Meseros.setVisible(true);
        MesaPrincipal.setVisible(false);
        Comparativa.setVisible(false);
        Reporte.setVisible(false);
        Sillas.setVisible(false);
        Mesas.setVisible(false);
    }//GEN-LAST:event_jMeserosMouseClicked

    private void jMeserosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMeserosMouseEntered
        jMenu.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jMeserosMouseEntered

    private void jMeserosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMeserosMouseExited
        jMenu.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMeserosMouseExited

    private void bSalirMeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirMeserosActionPerformed
        Productos.setVisible(false);
        Sillas.setVisible(false);
        MesaPrincipal.setVisible(false);
        Meseros.setVisible(false);
        Reporte.setVisible(false);
        Comparativa.setVisible(false);
        Mesas.setVisible(true);
    }//GEN-LAST:event_bSalirMeserosActionPerformed

    private void bSalirMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirMesasActionPerformed
        Productos.setVisible(false);
        Sillas.setVisible(false);
        MesaPrincipal.setVisible(false);
        Reporte.setVisible(false);
        Meseros.setVisible(false);
        Comparativa.setVisible(false);
        Mesas.setVisible(true);
    }//GEN-LAST:event_bSalirMesasActionPerformed

    private void bSalirComparativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirComparativaActionPerformed
        Productos.setVisible(false);
        Sillas.setVisible(false);
        Reporte.setVisible(false);
        Meseros.setVisible(false);
        MesaPrincipal.setVisible(false);
        Comparativa.setVisible(false);
        Mesas.setVisible(true);
    }//GEN-LAST:event_bSalirComparativaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ya se realiso la comparativa");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bSalirMesasPrincipalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirMesasPrincipalesActionPerformed
        Productos.setVisible(false);
        MesaPrincipal.setVisible(false);
        Sillas.setVisible(false);
        Meseros.setVisible(false);
        Reporte.setVisible(false);
        Comparativa.setVisible(false);
        Mesas.setVisible(true);
    }//GEN-LAST:event_bSalirMesasPrincipalesActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCancelarActionPerformed

    private void jCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCategoriaActionPerformed

    private void bSalirReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirReporteActionPerformed
        Productos.setVisible(false);
        MesaPrincipal.setVisible(false);
        Sillas.setVisible(false);
        Meseros.setVisible(false);
        Reporte.setVisible(false);
        Comparativa.setVisible(false);
        Mesas.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_bSalirReporteActionPerformed

    private void bSalirReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalirReporteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bSalirReporteMouseClicked

    private void bRegistrarMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarMeseroActionPerformed
        String id_S = tID_Meseros.getText();
        int idM = Integer.parseInt(id_S);
        String nombre = tNombre_Mesero.getText();
        String apellidoP = tApellidoP.getText();
        String apellidoM = tApellidoM.getText();
        this.agregarMesero(idM, nombre, apellidoP, apellidoM);
    }//GEN-LAST:event_bRegistrarMeseroActionPerformed

    private void tNombre_MeseroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNombre_MeseroFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombre_MeseroFocusGained

    private void bEliminarMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarMeseroActionPerformed
        JOptionPane.showMessageDialog(null, "Proximamente...");
    }//GEN-LAST:event_bEliminarMeseroActionPerformed

    private void bSalirProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalirProductosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bSalirProductosMouseClicked

    private void bSalirProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirProductosActionPerformed
        Productos.setVisible(false);
    }//GEN-LAST:event_bSalirProductosActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Productos.setVisible(false);
        Sillas.setVisible(false);
        MesaPrincipal.setVisible(false);
        Meseros.setVisible(false);
        Reporte.setVisible(false);
        Comparativa.setVisible(false);
        Mesas.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void bRegistrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarCategoriaActionPerformed
        int id_categoria = Integer.parseInt(tIDCategoria.getText());
        String nombre_categoria = tEscribirCategoria.getText();
        this.agregarCategoria(id_categoria, nombre_categoria);
    }//GEN-LAST:event_bRegistrarCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beta_Galera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beta_Galera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beta_Galera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beta_Galera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beta_Galera().setVisible(true);
            }
        });
    }
    
    public int inicio(){
        int duracion = 5;
        final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
        final Runnable runnable = new Runnable(){
            int countdownStarter = duracion;
            public void run(){
                switch(countdownStarter){
                    case 5:
                        jInicioSesion.setVisible(true);
                        break;
                    case 2:
                        deslice.desplazarDerecha(jInicioSesion, jInicioSesion.getX(), 2000, 30, 1);
                        break;
                }
                countdownStarter--;
                if(countdownStarter<1){
                    try {
                        Thread.sleep(1000);
                        jInicioSesion.setVisible(false);
                        jMenu.setVisible(true);
                        jTiempo1.setText("Ultima sesion: "+tiempo.getDayOfMonth()+"/"+tiempo.getMonth()+"/"+tiempo.getYear()+" "+tiempo.getHour()+":"+tiempo.getMinute()+":"+tiempo.getSecond());
                        Mesas.setVisible(true);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        scheduler.scheduleAtFixedRate(runnable, 0, 1, SECONDS);
        return 0;
    }
    
    public void mostrarMeseros(){
        String apellido_materno,apellido_paterno,nombre;
        try{
            String[] titulos={"Nombre","Apellido Paterno","Apellido Materno"};
            String[] registro = new String[3];
            DefaultTableModel modelo = new DefaultTableModel(null, titulos);
            ConexionBD con = new ConexionBD();
            try{
                Statement status = con.getConecction().createStatement();
                status.executeQuery("Select * from empleados order by id_empleado desc;");
                ResultSet rs = null;
                rs = status.getResultSet();
                while(rs.next()){
                    registro[0] = rs.getString("nombre_empleado");
                    registro[1] = rs.getString("apellido_paterno");
                    registro[2] = rs.getString("apellido_materno");
                    modelo.addRow(registro);
                }
                tmostrarMeseros.setModel(modelo);
                status.close();
                rs.close();
                con.desconectar();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "No se puede mostrar el mesero: ("+ e.getMessage()+")");
            }
        }catch(SQLException ex){
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE,null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public int generarIDMeseros(int id){
        try {
            ConexionBD con = new ConexionBD();
            Statement status = con.getConecction().createStatement();
            status.executeQuery("Select max(id_empleado) id from empleados;");
            ResultSet rs = null;
            rs = status.getResultSet();
            while(rs.next()){
                id = rs.getInt("id");
            }
            status.close();
            rs.close();
            con.desconectar();
        } catch (SQLException ex) {
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id+1;
    }
    
    public void agregarMesero(int id, String nombre, String apellido_paterno, String apellido_materno){
        try {
            try{
                ConexionBD con = new ConexionBD();
                Statement status = con.getConecction().createStatement();
                status.executeUpdate("INSERT INTO empleados (id_empleado, nombre_empleado, apellido_paterno, apellido_materno) VALUES ('"+id+"', '"+nombre+"', '"+apellido_paterno+"', '"+apellido_materno+"');");
                JOptionPane.showMessageDialog(null, "Se registro correctamente");
                tNombre_Mesero.setText("");
                tApellidoP.setText("");
                tApellidoM.setText("");
                tID_Meseros.setText(""+this.generarIDMeseros(id));
                this.mostrarMeseros();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "No se puede registrar ("+ e.getMessage()+")");
                tNombre_Mesero.setText("");
                tApellidoP.setText("");
                tApellidoM.setText("");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public int generarIDCategoria(int id){
        try {
            ConexionBD con = new ConexionBD();
            Statement status = con.getConecction().createStatement();
            status.executeQuery("Select max(id_categoria) id from categoria_productos;");
            ResultSet rs = null;
            rs = status.getResultSet();
            while(rs.next()){
                id = rs.getInt("id");
            }
            status.close();
            rs.close();
            con.desconectar();
        } catch (SQLException ex) {
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id+1;
    }
    
    public int generarIDProducto(int id){
        try {
            ConexionBD con = new ConexionBD();
            Statement status = con.getConecction().createStatement();
            status.executeQuery("Select max(id_productos) id from productos;");
            ResultSet rs = null;
            rs = status.getResultSet();
            while(rs.next()){
                id = rs.getInt("id");
            }
            status.close();
            rs.close();
            con.desconectar();
        } catch (SQLException ex) {
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id+1;
    }
    
    public void mostrarCategoria(){
        String apellido_materno,apellido_paterno,nombre;
        try{
            String[] titulos={"id","nombre_categorias"};
            String[] registro = new String[2];
            DefaultTableModel modelo = new DefaultTableModel(null, titulos);
            ConexionBD con = new ConexionBD();
            try{
                Statement status = con.getConecction().createStatement();
                status.executeQuery("Select * from categoria_productos;");
                ResultSet rs = null;
                rs = status.getResultSet();
                while(rs.next()){
                    registro[0] = rs.getString("id_categoria");
                    registro[1] = rs.getString("nombre_categoria");
                    modelo.addRow(registro);
                }
                tTablaCategoria.setModel(modelo);
                status.close();
                rs.close();
                con.desconectar();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "No se puede mostrar el mesero: ("+ e.getMessage()+")");
            }
        }catch(SQLException ex){
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE,null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void agregarCategoria(int id, String nombre_categoria){
        try {
            try{
                ConexionBD con = new ConexionBD();
                Statement status = con.getConecction().createStatement();
                status.executeUpdate("INSERT INTO categoria_productos (id_categoria, nombre_categoria) VALUES ('"+id+"', '"+nombre_categoria+"');");
                JOptionPane.showMessageDialog(null, "Se registro correctamente");
                tEscribirCategoria.setText("");
                tIDCategoria.setText(""+this.generarIDCategoria(id));
                this.mostrarCategoria();
                jCategoriaProducto.removeAllItems();
                this.cargarComboCategorias();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "No se puede registrar ("+ e.getMessage()+")");
                tEscribirCategoria.setText("");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public ArrayList<MeserosVO> llamarMeseros() throws SQLException, ClassNotFoundException{
        ArrayList<MeserosVO> misMeseros = new ArrayList<MeserosVO>();
        ConexionBD con = new ConexionBD();
        try{
            Statement status = con.getConecction().createStatement();
            status.executeQuery("Select * from empleados order by id_empleado desc;");
            ResultSet rs = null;
            rs = status.getResultSet();
            while(rs.next()){
                MeserosVO meseros = new MeserosVO();
                meseros.setId(rs.getInt("id_empleado"));
                meseros.setNombre(rs.getString("nombre_empleado"));
                meseros.setApellido_paterno(rs.getString("apellido_paterno"));
                meseros.setApellido_materno(rs.getString("apellido_materno"));
                misMeseros.add(meseros);
            }
            status.close();
            rs.close();
            con.desconectar();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "No se puede mostrar el mesero: ("+ e.getMessage()+")");
        }
        return misMeseros;
    }
    
    public ArrayList<categoriaVO> llamarCategorias() throws SQLException, ClassNotFoundException{
        ArrayList<categoriaVO> misCategoria = new ArrayList<categoriaVO>();
        ConexionBD con = new ConexionBD();
        try{
            Statement status = con.getConecction().createStatement();
            status.executeQuery("Select * from categoria_productos order by id_categoria desc;");
            ResultSet rs = null;
            rs = status.getResultSet();
            while(rs.next()){
                categoriaVO categoria = new categoriaVO();
                categoria.setId_categoria(rs.getInt("id_categoria"));
                categoria.setId_nombre_categoria(rs.getString("nombre_categoria"));
                misCategoria.add(categoria);
            }
            status.close();
            rs.close();
            con.desconectar();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "No se puede mostrar el mesero: ("+ e.getMessage()+")");
        }
        return misCategoria;
    }
    
    public void mostrarProducto(){
        String apellido_materno,apellido_paterno,nombre;
        try{
            String[] titulos={"ID","Nombre producto","Categoria", "Precio"};
            String[] registro = new String[4];
            DefaultTableModel modelo = new DefaultTableModel(null, titulos);
            ConexionBD con = new ConexionBD();
            try{
                Statement status = con.getConecction().createStatement();
                status.executeQuery("Select * from productos;");
                ResultSet rs = null;
                rs = status.getResultSet();
                while(rs.next()){
                    registro[0] = rs.getString("id_productos");
                    registro[1] = rs.getString("nombre_producto");
                    registro[2] = rs.getString("fk_id_categoria");
                    registro[3] = rs.getString("precio");
                    modelo.addRow(registro);
                }
                tTablaProducto.setModel(modelo);
                status.close();
                rs.close();
                con.desconectar();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "No se puede mostrar el mesero: ("+ e.getMessage()+")");
            }
        }catch(SQLException ex){
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE,null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void cargarComboCategorias() throws SQLException, ClassNotFoundException{
        categoriaVO categoriaVO;
        ArrayList <categoriaVO> misCategorias = this.llamarCategorias();
        for (int i = 0; i < misCategorias.size(); i++) {
            jCategoriaProducto.addItem(misCategorias.get(i).getId_nombre_categoria());
        }
    }
    
    int id;
    LocalDateTime tiempo = LocalDateTime.now();
    Desface deslice = new Desface();
    boolean mesas,comparativa,productos,reporte,meseros;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Comparativa;
    private javax.swing.JLabel FechaActualMesero;
    private javax.swing.JButton JPagar;
    private javax.swing.JComboBox<String> JProducto;
    private javax.swing.JLabel Mesa1;
    private javax.swing.JLabel Mesa2;
    private javax.swing.JLabel Mesa3;
    private javax.swing.JLabel Mesa4;
    private javax.swing.JLabel Mesa5;
    private javax.swing.JPanel MesaPrincipal;
    private javax.swing.JTable MesaTabla;
    private javax.swing.JTable MesaTabla1;
    private javax.swing.JPanel Mesas;
    private javax.swing.JPanel Meseros;
    private javax.swing.JPanel Productos;
    private javax.swing.JPanel Reporte;
    private javax.swing.JPanel Sillas;
    private javax.swing.JButton bEliminarMesero;
    private javax.swing.JButton bRegistrarCategoria;
    private javax.swing.JButton bRegistrarMesero;
    private javax.swing.JButton bSalirComparativa;
    private javax.swing.JButton bSalirMesas;
    private javax.swing.JButton bSalirMesasPrincipales;
    private javax.swing.JButton bSalirMeseros;
    private javax.swing.JButton bSalirProductos;
    private javax.swing.JButton bSalirReporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jCancelar;
    private javax.swing.JComboBox<String> jCategoria;
    private javax.swing.JComboBox<String> jCategoriaProducto;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jComparativa;
    private javax.swing.JPanel jInicio;
    private javax.swing.JPanel jInicioSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jMenu;
    private javax.swing.JLabel jMesas;
    private javax.swing.JLabel jMeseros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPreInformacion;
    private javax.swing.JLabel jProductos;
    private javax.swing.JLabel jReporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel jTiempo;
    private javax.swing.JLabel jTiempo1;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JPanel panelMesero1;
    private javax.swing.JPanel panelMesero2;
    private javax.swing.JPanel panelMesero3;
    private javax.swing.JPanel panelMesero4;
    private javax.swing.JPanel panelMesero5;
    private javax.swing.JPanel panelMesero6;
    private javax.swing.JTextField tApellidoM;
    private javax.swing.JTextField tApellidoP;
    private javax.swing.JTextField tEscribirCategoria;
    private javax.swing.JTextField tEscribirCategoria2;
    private javax.swing.JTextField tEscribirCategoria3;
    private javax.swing.JTextField tIDCategoria;
    private javax.swing.JTextField tID_Meseros;
    private javax.swing.JTextField tID_Productos;
    private javax.swing.JTextField tNombre_Mesero;
    private javax.swing.JTable tTablaCategoria;
    private javax.swing.JTable tTablaProducto;
    private javax.swing.JTable tmostrarMeseros;
    // End of variables declaration//GEN-END:variables
}