/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_galera;

import java.awt.Frame;
import java.time.LocalDateTime;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import static java.util.concurrent.TimeUnit.SECONDS;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import desplazable.Desface;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author cdani
 */
public class Beta_Galera extends javax.swing.JFrame {

    /**
     * Creates new form Beta_Galera
     */
    public Beta_Galera() {
        initComponents();
        jInicioSesion.setVisible(false);
        Meseros.setVisible(false);
        Mesas.setVisible(false);
        System.out.println("Hola");
        Sillas.setVisible(false);
        Comparativa.setVisible(false);
        jPreInformacion.setVisible(false);
        Mesas.setVisible(false);
        this.inicio();
        jTiempo.setText("Ultima sesion: "+tiempo.getDayOfMonth()+"/"+tiempo.getMonth()+"/"+tiempo.getYear()+" "+tiempo.getHour()+":"+tiempo.getMinute()+":"+tiempo.getSecond());
        FechaActualMesero.setText("Fecha actual: "+tiempo.getDayOfMonth()+"/"+tiempo.getMonth()+"/"+tiempo.getYear());
        try {   
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAbdFeel");
        } catch (Exception e) {
        } 
         this.setExtendedState(Frame.MAXIMIZED_BOTH);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInicio = new javax.swing.JPanel();
        Comparativa = new javax.swing.JPanel();
        bSalirComparativa = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        panelMesero3 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        Sillas = new javax.swing.JPanel();
        bSalirMesas = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        panelMesero2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        Meseros = new javax.swing.JPanel();
        bSalirMeseros = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelMesero1 = new javax.swing.JPanel();
        FechaActualMesero = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPreInformacion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTiempo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenu = new javax.swing.JPanel();
        jTitulo = new javax.swing.JLabel();
        jMesas = new javax.swing.JLabel();
        jComparativa = new javax.swing.JLabel();
        jProductos = new javax.swing.JLabel();
        jReporte = new javax.swing.JLabel();
        jMeseros = new javax.swing.JLabel();
        jInicioSesion = new javax.swing.JPanel();
        jTiempo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Mesas = new javax.swing.JPanel();
        Mesa1 = new javax.swing.JLabel();
        Mesa2 = new javax.swing.JLabel();
        Mesa3 = new javax.swing.JLabel();
        Mesa4 = new javax.swing.JLabel();
        Mesa5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInicio.setBackground(new java.awt.Color(255, 255, 255));
        jInicio.setLayout(null);

        Comparativa.setBackground(new java.awt.Color(255, 255, 255));
        Comparativa.setLayout(null);

        bSalirComparativa.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bSalirComparativa.setForeground(new java.awt.Color(255, 255, 255));
        bSalirComparativa.setText("X");
        bSalirComparativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirComparativaActionPerformed(evt);
            }
        });
        Comparativa.add(bSalirComparativa);
        bSalirComparativa.setBounds(1280, 10, 90, 60);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel21.setText("Comparativa");
        Comparativa.add(jLabel21);
        jLabel21.setBounds(670, 0, 400, 80);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        Comparativa.add(jPanel6);
        jPanel6.setBounds(360, 10, 10, 610);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        Comparativa.add(jPanel7);
        jPanel7.setBounds(0, 0, 1400, 10);

        panelMesero3.setBackground(new java.awt.Color(255, 255, 0));
        panelMesero3.setLayout(null);

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel37.setText("------------RELLENO-------------");
        panelMesero3.add(jLabel37);
        jLabel37.setBounds(50, 560, 250, 40);

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel42.setText("Resultado comparativa:");
        panelMesero3.add(jLabel42);
        jLabel42.setBounds(40, 30, 290, 40);

        jLabel43.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel43.setText("Producto 1 (Name): $$$");
        panelMesero3.add(jLabel43);
        jLabel43.setBounds(30, 140, 210, 40);

        jLabel44.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel44.setText("Producto 2 (Name): $$$");
        panelMesero3.add(jLabel44);
        jLabel44.setBounds(30, 230, 220, 40);

        jLabel45.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel45.setText("------------RELLENO-------------");
        panelMesero3.add(jLabel45);
        jLabel45.setBounds(50, 380, 250, 40);

        jLabel46.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel46.setText("------------RELLENO-------------");
        panelMesero3.add(jLabel46);
        jLabel46.setBounds(50, 470, 250, 40);

        Comparativa.add(panelMesero3);
        panelMesero3.setBounds(0, 0, 360, 620);

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel38.setText("VERSION INTERFACE 1.1");
        Comparativa.add(jLabel38);
        jLabel38.setBounds(1150, 580, 250, 30);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Comparativa.add(jComboBox5);
        jComboBox5.setBounds(900, 160, 270, 30);

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel39.setText("Seleccione el producto 1:");
        Comparativa.add(jLabel39);
        jLabel39.setBounds(420, 310, 300, 70);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Comparativa.add(jComboBox6);
        jComboBox6.setBounds(730, 330, 270, 30);

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel40.setText("Seleccione el producto 2:");
        Comparativa.add(jLabel40);
        jLabel40.setBounds(440, 420, 300, 70);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Comparativa.add(jComboBox7);
        jComboBox7.setBounds(750, 440, 270, 30);

        jLabel8.setText("La cantidad de producto: number_producto");
        Comparativa.add(jLabel8);
        jLabel8.setBounds(1050, 430, 290, 40);

        jLabel27.setText("La cantidad de producto: number_producto");
        Comparativa.add(jLabel27);
        jLabel27.setBounds(1040, 320, 290, 40);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        Comparativa.add(jSeparator1);
        jSeparator1.setBounds(370, 242, 1000, 10);

        jButton3.setText("Enviar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Comparativa.add(jButton3);
        jButton3.setBounds(700, 550, 240, 50);

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel41.setText("Seleccione la categoria del producto:");
        Comparativa.add(jLabel41);
        jLabel41.setBounds(450, 140, 430, 70);

        jInicio.add(Comparativa);
        Comparativa.setBounds(0, 90, 1370, 620);

        Sillas.setBackground(new java.awt.Color(255, 255, 255));
        Sillas.setLayout(null);

        bSalirMesas.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bSalirMesas.setForeground(new java.awt.Color(255, 255, 255));
        bSalirMesas.setText("X");
        bSalirMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirMesasActionPerformed(evt);
            }
        });
        Sillas.add(bSalirMesas);
        bSalirMesas.setBounds(1280, 10, 90, 60);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel20.setText("JUNTAR MESAS");
        Sillas.add(jLabel20);
        jLabel20.setBounds(620, 0, 400, 80);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        Sillas.add(jPanel4);
        jPanel4.setBounds(140, 10, 10, 610);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        Sillas.add(jPanel5);
        jPanel5.setBounds(0, 0, 1400, 10);

        panelMesero2.setBackground(new java.awt.Color(255, 255, 0));
        panelMesero2.setLayout(null);

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel22.setText("S");
        panelMesero2.add(jLabel22);
        jLabel22.setBounds(30, 500, 100, 90);

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel23.setText("M");
        panelMesero2.add(jLabel23);
        jLabel23.setBounds(20, 20, 100, 90);

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel24.setText("E");
        panelMesero2.add(jLabel24);
        jLabel24.setBounds(30, 140, 100, 90);

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel25.setText("S");
        panelMesero2.add(jLabel25);
        jLabel25.setBounds(30, 260, 70, 90);

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Dialog", 1, 100)); // NOI18N
        jLabel26.setText("A");
        panelMesero2.add(jLabel26);
        jLabel26.setBounds(30, 380, 100, 90);

        Sillas.add(panelMesero2);
        panelMesero2.setBounds(0, 0, 140, 620);

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel28.setText("Seleccione las mesa 1:");
        Sillas.add(jLabel28);
        jLabel28.setBounds(220, 130, 270, 60);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Juntar");
        Sillas.add(jButton4);
        jButton4.setBounds(670, 390, 220, 70);

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel31.setText("VERSION INTERFACE 1.1");
        Sillas.add(jLabel31);
        jLabel31.setBounds(1150, 580, 250, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Sillas.add(jComboBox1);
        jComboBox1.setBounds(1040, 140, 140, 40);

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel32.setText("Seleccione las mesa 2:");
        Sillas.add(jLabel32);
        jLabel32.setBounds(770, 130, 270, 60);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Sillas.add(jComboBox2);
        jComboBox2.setBounds(500, 140, 140, 40);

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel29.setText("Seleccione las mesa 3:");
        Sillas.add(jLabel29);
        jLabel29.setBounds(220, 240, 270, 60);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Sillas.add(jComboBox3);
        jComboBox3.setBounds(500, 250, 140, 40);

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel30.setText("Seleccione las mesa 4:");
        Sillas.add(jLabel30);
        jLabel30.setBounds(770, 240, 270, 60);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Sillas.add(jComboBox4);
        jComboBox4.setBounds(1050, 250, 140, 40);

        jInicio.add(Sillas);
        Sillas.setBounds(0, 90, 1370, 620);

        Meseros.setBackground(new java.awt.Color(255, 255, 255));
        Meseros.setLayout(null);

        bSalirMeseros.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bSalirMeseros.setForeground(new java.awt.Color(255, 255, 255));
        bSalirMeseros.setText("X");
        bSalirMeseros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirMeserosActionPerformed(evt);
            }
        });
        Meseros.add(bSalirMeseros);
        bSalirMeseros.setBounds(1280, 10, 90, 60);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel7.setText("MESEROS");
        Meseros.add(jLabel7);
        jLabel7.setBounds(730, 0, 260, 80);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("ID unico:");
        Meseros.add(jLabel9);
        jLabel9.setBounds(990, 140, 110, 50);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField1.setToolTipText("Escriba");
        Meseros.add(jTextField1);
        jTextField1.setBounds(1100, 150, 210, 30);

        jTextField2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField2.setToolTipText("Escriba");
        Meseros.add(jTextField2);
        jTextField2.setBounds(670, 150, 260, 30);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        Meseros.add(jPanel3);
        jPanel3.setBounds(290, 10, 10, 610);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        Meseros.add(jPanel2);
        jPanel2.setBounds(0, 0, 1400, 10);

        panelMesero1.setBackground(new java.awt.Color(255, 255, 0));
        panelMesero1.setLayout(null);

        FechaActualMesero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FechaActualMesero.setText("Fecha actual:");
        panelMesero1.add(FechaActualMesero);
        FechaActualMesero.setBounds(20, 420, 270, 40);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("Nombre_MESERO 5");
        panelMesero1.add(jLabel13);
        jLabel13.setBounds(20, 340, 190, 30);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("Nombre_MESERO 1");
        panelMesero1.add(jLabel14);
        jLabel14.setBounds(20, 100, 190, 30);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("Nombre_MESERO 2");
        panelMesero1.add(jLabel15);
        jLabel15.setBounds(20, 160, 190, 30);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("Nombre_MESERO 3");
        panelMesero1.add(jLabel16);
        jLabel16.setBounds(20, 220, 190, 30);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setText("Nombre_MESERO 4");
        panelMesero1.add(jLabel17);
        jLabel17.setBounds(20, 280, 190, 30);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Meseros actuales");
        panelMesero1.add(jLabel18);
        jLabel18.setBounds(10, 10, 270, 50);

        Meseros.add(panelMesero1);
        panelMesero1.setBounds(0, 0, 290, 620);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Nombre(s) del mesero:");
        Meseros.add(jLabel11);
        jLabel11.setBounds(400, 140, 270, 50);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("Apellido paterno:");
        Meseros.add(jLabel12);
        jLabel12.setBounds(410, 290, 210, 50);

        jTextField3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField3.setToolTipText("Escriba");
        Meseros.add(jTextField3);
        jTextField3.setBounds(620, 300, 220, 30);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setText("Apellido materno:");
        Meseros.add(jLabel19);
        jLabel19.setBounds(890, 290, 210, 50);

        jTextField4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField4.setToolTipText("Escriba");
        Meseros.add(jTextField4);
        jTextField4.setBounds(1100, 300, 210, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar");
        Meseros.add(jButton1);
        jButton1.setBounds(970, 460, 220, 70);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Eliminar usuario");
        Meseros.add(jButton2);
        jButton2.setBounds(600, 460, 220, 70);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("VERSION INTERFACE 1.1");
        Meseros.add(jLabel10);
        jLabel10.setBounds(1150, 580, 250, 30);

        jInicio.add(Meseros);
        Meseros.setBounds(0, 90, 1370, 620);

        jPreInformacion.setBackground(new java.awt.Color(0, 153, 255));
        jPreInformacion.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Gastado: $0");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 220, 120, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Numero de mesa: number");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 150, 240, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Estatus: Activo");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 80, 150, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Informacion prevista de la mesa");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 10, 320, 30);

        jPreInformacion.add(jPanel1);
        jPanel1.setBounds(20, 10, 320, 600);

        jInicio.add(jPreInformacion);
        jPreInformacion.setBounds(1020, 90, 360, 620);

        jTiempo1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jInicio.add(jTiempo1);
        jTiempo1.setBounds(1150, 680, 230, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("VERSION BETA 1.00");
        jInicio.add(jLabel2);
        jLabel2.setBounds(1130, 650, 240, 50);

        jMenu.setBackground(new java.awt.Color(255, 255, 0));
        jMenu.setLayout(null);

        jTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/1663952285593 (2).png"))); // NOI18N
        jTitulo.setText("PROJECT_GALERAS");
        jMenu.add(jTitulo);
        jTitulo.setBounds(20, 0, 440, 90);

        jMesas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/imagen_2022-09-26_113114959.png"))); // NOI18N
        jMesas.setText("Mesas");
        jMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMesasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMesasMouseExited(evt);
            }
        });
        jMenu.add(jMesas);
        jMesas.setBounds(480, 30, 100, 30);

        jComparativa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComparativa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/imagen_2022-10-03_100700234.png"))); // NOI18N
        jComparativa.setText("Comparativa");
        jComparativa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComparativaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComparativaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComparativaMouseExited(evt);
            }
        });
        jMenu.add(jComparativa);
        jComparativa.setBounds(610, 30, 160, 30);

        jProductos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/imagen_2022-10-03_094538812.png"))); // NOI18N
        jProductos.setText("Productos");
        jProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jProductosMouseExited(evt);
            }
        });
        jMenu.add(jProductos);
        jProductos.setBounds(800, 30, 130, 30);

        jReporte.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/imagen_2022-09-26_235325867.png"))); // NOI18N
        jReporte.setText("Reporte");
        jReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jReporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jReporteMouseExited(evt);
            }
        });
        jMenu.add(jReporte);
        jReporte.setBounds(970, 30, 110, 30);

        jMeseros.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMeseros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/imagen_2022-10-19_100343372.png"))); // NOI18N
        jMeseros.setText("Meseros");
        jMeseros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMeserosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMeserosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMeserosMouseExited(evt);
            }
        });
        jMenu.add(jMeseros);
        jMeseros.setBounds(1120, 30, 110, 30);

        jInicio.add(jMenu);
        jMenu.setBounds(10, 0, 1370, 90);

        jInicioSesion.setLayout(null);

        jTiempo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jInicioSesion.add(jTiempo);
        jTiempo.setBounds(460, 60, 480, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3.setText("BIENVENIDO A GALERAS");
        jInicioSesion.add(jLabel3);
        jLabel3.setBounds(390, 0, 590, 60);

        jInicio.add(jInicioSesion);
        jInicioSesion.setBounds(10, 310, 1370, 110);

        Mesas.setBackground(new java.awt.Color(255, 255, 255));
        Mesas.setLayout(null);

        Mesa1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Mesa1.setText("Mesa 1");
        Mesa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mesa1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mesa1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Mesa1MouseExited(evt);
            }
        });
        Mesas.add(Mesa1);
        Mesa1.setBounds(30, 40, 80, 30);

        Mesa2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Mesa2.setText("Mesa 2");
        Mesa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mesa2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mesa2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Mesa2MouseExited(evt);
            }
        });
        Mesas.add(Mesa2);
        Mesa2.setBounds(150, 40, 90, 30);

        Mesa3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Mesa3.setText("Mesa 3");
        Mesa3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mesa3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mesa3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Mesa3MouseExited(evt);
            }
        });
        Mesas.add(Mesa3);
        Mesa3.setBounds(270, 40, 90, 30);

        Mesa4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Mesa4.setText("Mesa 4");
        Mesa4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mesa4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mesa4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Mesa4MouseExited(evt);
            }
        });
        Mesas.add(Mesa4);
        Mesa4.setBounds(390, 40, 90, 30);

        Mesa5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Mesa5.setText("Mesa 5");
        Mesa5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mesa5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mesa5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Mesa5MouseExited(evt);
            }
        });
        Mesas.add(Mesa5);
        Mesa5.setBounds(520, 40, 90, 30);

        jInicio.add(Mesas);
        Mesas.setBounds(10, 90, 1370, 620);

        getContentPane().add(jInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1380, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMesasMouseEntered
        jMenu.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jMesasMouseEntered

    private void jMesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMesasMouseExited
        jMenu.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMesasMouseExited

    private void jMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMesasMouseClicked
        Sillas.setVisible(true);
        Meseros.setVisible(false);
        Comparativa.setVisible(false);
    }//GEN-LAST:event_jMesasMouseClicked

    private void jComparativaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComparativaMouseClicked
        Comparativa.setVisible(true);
        Sillas.setVisible(false);
        Meseros.setVisible(false);
        Mesas.setVisible(false);
    }//GEN-LAST:event_jComparativaMouseClicked

    private void jComparativaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComparativaMouseEntered
        jMenu.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jComparativaMouseEntered

    private void jComparativaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComparativaMouseExited
        jMenu.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jComparativaMouseExited

    private void jProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProductosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jProductosMouseClicked

    private void jProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProductosMouseEntered
        jMenu.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jProductosMouseEntered

    private void jProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProductosMouseExited
        jMenu.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jProductosMouseExited

    private void jReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jReporteMouseClicked

    }//GEN-LAST:event_jReporteMouseClicked

    private void jReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jReporteMouseEntered
        jMenu.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jReporteMouseEntered

    private void jReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jReporteMouseExited
        jMenu.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jReporteMouseExited

    private void Mesa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa1MouseClicked


    }//GEN-LAST:event_Mesa1MouseClicked

    private void Mesa1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa1MouseEntered
        Mesas.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jPreInformacion.setVisible(true);
    }//GEN-LAST:event_Mesa1MouseEntered

    private void Mesa1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa1MouseExited
        Mesas.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        jPreInformacion.setVisible(false);
    }//GEN-LAST:event_Mesa1MouseExited

    private void Mesa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa2MouseClicked

    }//GEN-LAST:event_Mesa2MouseClicked

    private void Mesa2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa2MouseEntered
        Mesas.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Mesa2MouseEntered

    private void Mesa2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa2MouseExited
        Mesas.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));

    }//GEN-LAST:event_Mesa2MouseExited

    private void Mesa3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa3MouseClicked

    }//GEN-LAST:event_Mesa3MouseClicked

    private void Mesa3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa3MouseEntered
        Mesas.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Mesa3MouseEntered

    private void Mesa3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa3MouseExited
        Mesas.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_Mesa3MouseExited

    private void Mesa4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa4MouseClicked

    }//GEN-LAST:event_Mesa4MouseClicked

    private void Mesa4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa4MouseEntered
        Mesas.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Mesa4MouseEntered

    private void Mesa4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa4MouseExited
        Mesas.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_Mesa4MouseExited

    private void Mesa5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa5MouseClicked

    }//GEN-LAST:event_Mesa5MouseClicked

    private void Mesa5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa5MouseEntered
        
    }//GEN-LAST:event_Mesa5MouseEntered

    private void Mesa5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mesa5MouseExited
 ;
    }//GEN-LAST:event_Mesa5MouseExited

    private void jMeserosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMeserosMouseClicked
        Meseros.setVisible(true);
        Comparativa.setVisible(false);
        Sillas.setVisible(false);
        Mesas.setVisible(false);
    }//GEN-LAST:event_jMeserosMouseClicked

    private void jMeserosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMeserosMouseEntered
        jMenu.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jMeserosMouseEntered

    private void jMeserosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMeserosMouseExited
        jMenu.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jMeserosMouseExited

    private void bSalirMeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirMeserosActionPerformed
        Sillas.setVisible(false);
        Meseros.setVisible(false);
        Comparativa.setVisible(false);
        Mesas.setVisible(true);
    }//GEN-LAST:event_bSalirMeserosActionPerformed

    private void bSalirMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirMesasActionPerformed
        Sillas.setVisible(false);
        Meseros.setVisible(false);
        Comparativa.setVisible(false);
        Mesas.setVisible(true);
    }//GEN-LAST:event_bSalirMesasActionPerformed

    private void bSalirComparativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirComparativaActionPerformed
        Sillas.setVisible(false);
        Meseros.setVisible(false);
        Comparativa.setVisible(false);
        Mesas.setVisible(true);
    }//GEN-LAST:event_bSalirComparativaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ya se realiso la comparativa");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beta_Galera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beta_Galera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beta_Galera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beta_Galera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beta_Galera().setVisible(true);
            }
        });
    }
    
    public int inicio(){
        int duracion = 5;
        final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
        final Runnable runnable = new Runnable(){
            int countdownStarter = duracion;
            public void run(){
                switch(countdownStarter){
                    case 5:
                        jInicioSesion.setVisible(true);
                        break;
                    case 2:
                        deslice.desplazarDerecha(jInicioSesion, jInicioSesion.getX(), 2000, 30, 1);
                        break;
                }
                countdownStarter--;
                if(countdownStarter<1){
                    try {
                        Thread.sleep(1000);
                        jInicioSesion.setVisible(false);
                        jMenu.setVisible(true);
                        jTiempo1.setText("Ultima sesion: "+tiempo.getDayOfMonth()+"/"+tiempo.getMonth()+"/"+tiempo.getYear()+" "+tiempo.getHour()+":"+tiempo.getMinute()+":"+tiempo.getSecond());
                        Mesas.setVisible(true);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Beta_Galera.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        scheduler.scheduleAtFixedRate(runnable, 0, 1, SECONDS);
        return 0;
    }
    LocalDateTime tiempo = LocalDateTime.now();
    Desface deslice = new Desface();
    boolean mesas,comparativa,productos,reporte,meseros;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Comparativa;
    private javax.swing.JLabel FechaActualMesero;
    private javax.swing.JLabel Mesa1;
    private javax.swing.JLabel Mesa2;
    private javax.swing.JLabel Mesa3;
    private javax.swing.JLabel Mesa4;
    private javax.swing.JLabel Mesa5;
    private javax.swing.JPanel Mesas;
    private javax.swing.JPanel Meseros;
    private javax.swing.JPanel Sillas;
    private javax.swing.JButton bSalirComparativa;
    private javax.swing.JButton bSalirMesas;
    private javax.swing.JButton bSalirMeseros;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jComparativa;
    private javax.swing.JPanel jInicio;
    private javax.swing.JPanel jInicioSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jMenu;
    private javax.swing.JLabel jMesas;
    private javax.swing.JLabel jMeseros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPreInformacion;
    private javax.swing.JLabel jProductos;
    private javax.swing.JLabel jReporte;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel jTiempo;
    private javax.swing.JLabel jTiempo1;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JPanel panelMesero1;
    private javax.swing.JPanel panelMesero2;
    private javax.swing.JPanel panelMesero3;
    // End of variables declaration//GEN-END:variables
}