/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_galera;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author cdani
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        setIconImage(getIconImage());
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTitulo = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        tUser = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        tPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galeras | Iniciar Sesion");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(300, 20, 80, 50);

        jTitulo.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/1663952285593 (2).png"))); // NOI18N
        jTitulo.setText("GALERAS");
        jPanel2.add(jTitulo);
        jTitulo.setBounds(10, 0, 220, 90);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 90);

        jLabel65.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel65.setText("CORREO/USER:");
        jPanel1.add(jLabel65);
        jLabel65.setBounds(20, 190, 110, 40);

        jLabel66.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel66.setText("VERSION INTERFACE 1.0");
        jPanel1.add(jLabel66);
        jLabel66.setBounds(220, 440, 190, 30);
        jPanel1.add(tUser);
        tUser.setBounds(140, 200, 220, 30);

        jLabel67.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel67.setText("CONTRASEÑA:");
        jPanel1.add(jLabel67);
        jLabel67.setBounds(30, 270, 100, 30);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton2.setText("ENVIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(120, 350, 170, 60);

        jLabel68.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel68.setText("INICIO DE SESION");
        jPanel1.add(jLabel68);
        jLabel68.setBounds(90, 100, 220, 40);
        jPanel1.add(tPassword);
        tPassword.setBounds(140, 270, 220, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /*introGalera inicio = new introGalera();
        inicio.setVisible(true);
        this.setVisible(false);*/
        String usuario = tUser.getText();
        String password = tPassword.getText();
        this.verificarUsuario(usuario, password);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Icono/Logon.png"));
        return retValue;
    }
    
    public void verificarUsuario(String usuario, String password){
        String usuario1, password1;
        int id;
        try {
            ConexionBD con = new ConexionBD();
            Statement status = con.getConecction().createStatement();
            status.executeQuery("select usuario_sesion from inicio_sesion where usuario_sesion = '"+usuario+"';");
            status.executeQuery("select contrasena_sesion from inicio_sesion where contrasena_sesion = '"+password+"';");
            status.executeQuery("select id_sesion, usuario_sesion, contrasena_sesion from inicio_sesion where usuario_sesion = '"+usuario+"' && contrasena_sesion = '"+password+"';");
            ResultSet rs = null;
            rs = status.getResultSet();
            if(rs.next()){
                usuario1 = rs.getString("usuario_sesion");
                password1 = rs.getString("contrasena_sesion");
                id = rs.getInt("id_sesion");
                this.dispose();
                introGalera inicio = new introGalera();
                inicio.setVisible(true);
                rs.close();
                status.close();
                con.desconectar();
            }else{
                JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecta");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No existe el usuario ("+ex.getMessage()+")");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUser;
    // End of variables declaration//GEN-END:variables
}
