/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_galera;


import desplazable.Desface;
import java.awt.Color;
import java.util.logging.Level;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import ds.desktop.notify.DesktopNotify;
import java.awt.Cursor;
import java.awt.Frame;

/**
 *
 * @author cdani
 */
public class introGalera extends javax.swing.JFrame {
    private int aux=0;
    private boolean realizado = false;
    hilo ejecutar = new hilo();
    /**
     * Creates new form IntroSEM
     */
    public introGalera() {
        initComponents();
        Barra.setVisible(false);
        introGalera.this.getRootPane().setOpaque(false);
        introGalera.this.getContentPane().setBackground(new Color (0, 0, 0, 0));
        this.setResizable(false);
        this.setLocationRelativeTo(this);
        Galeras2.setVisible(false);
        Galeras3.setVisible(false);
        Version.setVisible(false);
        UIManager.put( "nimbusOrange", new Color(33, 27, 27) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Barra = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        Texto = new javax.swing.JLabel();
        Galeras1 = new javax.swing.JLabel();
        Galeras2 = new javax.swing.JLabel();
        Galeras3 = new javax.swing.JLabel();
        Version = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        Barra.setBackground(new java.awt.Color(255, 255, 255));
        Barra.setAutoscrolls(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(null);

        Texto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Texto.setForeground(new java.awt.Color(0, 0, 0));
        Texto.setText("VERSION BETA 1.30");
        jPanel1.add(Texto);
        Texto.setBounds(170, 220, 230, 20);

        Galeras1.setFont(new java.awt.Font("Rage Italic", 0, 130)); // NOI18N
        Galeras1.setForeground(new java.awt.Color(255, 255, 255));
        Galeras1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Galeras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/1663952285593 (1).png"))); // NOI18N
        jPanel1.add(Galeras1);
        Galeras1.setBounds(200, 60, 30, 40);

        Galeras2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/1663952285593 (2).png"))); // NOI18N
        jPanel1.add(Galeras2);
        Galeras2.setBounds(180, 30, 80, 100);

        Galeras3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galera/Imagen/1663952285593 (3).png"))); // NOI18N
        jPanel1.add(Galeras3);
        Galeras3.setBounds(150, 0, 150, 160);

        Version.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        Version.setForeground(new java.awt.Color(0, 0, 0));
        Version.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Version.setText("GALERAS");
        jPanel1.add(Version);
        Version.setBounds(70, 170, 260, 40);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(realizado == false){
            realizado = true;
            Barra.setMaximum(70);
            Barra.setMinimum(0);
            ejecutar.start();
        }
    }//GEN-LAST:event_formWindowActivated

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
       
    }//GEN-LAST:event_jPanel1FocusGained

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        jPanel1.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    }//GEN-LAST:event_jPanel1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(introGalera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(introGalera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(introGalera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(introGalera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new introGalera().setVisible(true);
            }
        });
    }
    private class hilo extends Thread{
        @Override
        public void run(){
            try {while(true){
                aux++;
                Barra.setValue(aux);
                repaint();
                switch(aux){
                    case 0:
                        
                        break;
                    case 3:
                        Galeras1.setVisible(true);
                        break;
                    case 5:
                        desplace.desplazarIzquierda(Texto, Texto.getX(), 5, 15, 1);
                        Galeras1.setVisible(false);
                        Galeras2.setVisible(true);
                        break;
                    case 6:
                        Galeras2.setVisible(false);
                        Galeras3.setVisible(true);
                        Version.setVisible(true);
                        break;
                    case 70:
                        //jPanel1.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                        Beta_Galera inicio = new Beta_Galera();
                        inicio.setExtendedState(Frame.MAXIMIZED_BOTH);
                        inicio.setVisible(true);
                        inicio.setLocationRelativeTo(introGalera.this);
                        introGalera.this.dispose();
                        ejecutar.stop();
                        break;
                }
                Thread.sleep(50);}
            } catch (InterruptedException ex) {
                java.util.logging.Logger.getLogger(introGalera.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    Desface desplace = new Desface();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Barra;
    private javax.swing.JLabel Galeras1;
    private javax.swing.JLabel Galeras2;
    private javax.swing.JLabel Galeras3;
    private javax.swing.JLabel Texto;
    private javax.swing.JLabel Version;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}